'use client'

import { useState, useMemo, useEffect } from 'react'
import { 
  FileText, 
  Plus, 
  Download, 
  Send, 
  CheckCircle, 
  AlertCircle, 
  DollarSign, 
  Calendar,
  Search,
  Filter,
  MoreVertical,
  ArrowUpRight,
  Clock,
  ShieldCheck,
  Zap,
  Printer,
  Mail,
  Trash2,
  ChevronRight,
  Wallet,
  User,
  Building2,
  Package,
  Calculator
} from 'lucide-react'

interface Client {
  id: number
  name: string
  company: string
  email: string
  phone: string
  location: string
  joinDate: string
  totalSpent: number
  projects: number
  lastService: string
  status: 'Active' | 'Inactive' | 'Suspended'
  tier: 'Platinum' | 'Gold' | 'Silver' | 'Bronze'
  notes: string
}

interface Service {
  id: number
  name: string
  description: string
  categoryId: number
  categoryName: string
  basePrice: number
  price?: number
  unit: string
  image?: string
  createdAt: string
  rating?: number
  duration?: string
  popularity?: number
  featured?: boolean
}

interface LineItem {
  id: number
  serviceId: number
  serviceName: string
  description: string
  quantity: number
  unitPrice: number
  unit: string
  total: number
}

export default function InvoiceGeneratorPage() {
  const [invoices, setInvoices] = useState<any[]>([
    {
      id: 1,
      invoiceNumber: 'INV-2025-001',
      clientId: 1,
      clientName: 'Acme Corporation',
      jobId: 1,
      serviceType: 'Deep Cleaning',
      invoiceDate: '2025-12-23',
      dueDate: '2026-01-23',
      status: 'Sent',
      lineItems: [
        { description: 'Deep Cleaning Service (4 hours)', quantity: 1, unitPrice: 1000.00 },
        { description: 'Carpet Stain Removal', quantity: 2, unitPrice: 75.00 },
        { description: 'Floor Waxing', quantity: 1, unitPrice: 100.00 }
      ],
      subtotal: 1250.00,
      tax: 125.00,
      total: 1375.00,
      vatRate: 0.10,
      currencyCode: 'AED',
      paymentTerms: '30 days',
      notes: 'Payment due within 30 days of invoice date. Bank details included below.',
      autoGenerated: true,
      sentAt: '2025-12-23 15:45',
      paymentStatus: 'Pending',
      partialPayments: []
    },
    {
      id: 2,
      invoiceNumber: 'INV-2025-002',
      clientId: 2,
      clientName: 'Tech Solutions Inc',
      jobId: 2,
      serviceType: 'Office Maintenance',
      invoiceDate: '2025-12-22',
      dueDate: '2026-01-22',
      status: 'Paid',
      lineItems: [
        { description: 'Office Maintenance Service (3.75 hours)', quantity: 1, unitPrice: 750.00 },
        { description: 'Restroom Sanitization', quantity: 1, unitPrice: 75.00 },
        { description: 'Kitchen Deep Clean', quantity: 1, unitPrice: 70.00 }
      ],
      subtotal: 895.00,
      tax: 89.50,
      total: 984.50,
      vatRate: 0.10,
      currencyCode: 'AED',
      paymentTerms: '15 days',
      notes: 'Thank you for your business!',
      autoGenerated: true,
      sentAt: '2025-12-22 17:30',
      paymentStatus: 'Paid',
      paidAt: '2025-12-24',
      partialPayments: [
        { date: '2025-12-24', amount: 984.50 }
      ]
    },
    {
      id: 3,
      invoiceNumber: 'INV-2025-003',
      clientId: 3,
      clientName: 'Medical Center West',
      jobId: 3,
      serviceType: 'Post-Construction Cleaning',
      invoiceDate: '2025-12-21',
      dueDate: '2026-01-04',
      status: 'Draft',
      lineItems: [
        { description: 'Post-Construction Cleaning (5.5 hours)', quantity: 1, unitPrice: 1800.00 },
        { description: 'Debris Removal', quantity: 1, unitPrice: 200.00 },
        { description: 'Final Inspection & Walkthrough', quantity: 1, unitPrice: 150.00 }
      ],
      subtotal: 2150.00,
      tax: 215.00,
      total: 2365.00,
      vatRate: 0.10,
      currencyCode: 'AED',
      paymentTerms: '14 days',
      notes: 'Project completion invoice. Please verify all services before payment.',
      autoGenerated: true,
      sentAt: null,
      paymentStatus: 'Draft',
      partialPayments: []
    }
  ])

  const [selectedInvoiceId, setSelectedInvoiceId] = useState(1)
  const [showNewInvoiceModal, setShowNewInvoiceModal] = useState(false)
  const [clients, setClients] = useState<Client[]>([])
  const [services, setServices] = useState<Service[]>([])
  const [newInvoice, setNewInvoice] = useState({
    clientId: 0,
    clientName: '',
    clientCompany: '',
    clientEmail: '',
    clientPhone: '',
    clientLocation: '',
    serviceType: '',
    lineItems: [] as LineItem[],
    vatRate: 0.10,
    paymentTerms: '30',
    notes: '',
    discount: 0
  })

  const [showClientDropdown, setShowClientDropdown] = useState(false)
  const [showServiceDropdown, setShowServiceDropdown] = useState(false)
  const [clientSearchTerm, setClientSearchTerm] = useState('')
  const [serviceSearchTerm, setServiceSearchTerm] = useState('')

  // Load clients and services data
  useEffect(() => {
    loadClients()
    loadServices()
  }, [])

  const loadClients = () => {
    const savedClients = localStorage.getItem('homeware_crm_clients')
    if (savedClients) {
      setClients(JSON.parse(savedClients))
    } else {
      // Initialize with mock client data
      const mockClients: Client[] = [
        {
          id: 1,
          name: 'Ahmed Al-Mansouri',
          company: 'Dubai Properties LLC',
          email: 'ahmed@dubaiprop.ae',
          phone: '+971-50-1111111',
          location: 'Dubai Marina',
          joinDate: '2024-01-15',
          totalSpent: 275000,
          projects: 4,
          lastService: '2025-12-22',
          status: 'Active',
          tier: 'Gold',
          notes: 'Premium client, high satisfaction'
        },
        {
          id: 2,
          name: 'Layla Hassan',
          company: 'Paradise Hotels',
          email: 'layla@paradisehotels.ae',
          phone: '+971-50-4444444',
          location: 'Palm Jumeirah',
          joinDate: '2024-06-10',
          totalSpent: 450000,
          projects: 6,
          lastService: '2025-12-21',
          status: 'Active',
          tier: 'Platinum',
          notes: 'Strategic partner, regular volume'
        },
        {
          id: 3,
          name: 'Mohammed Al-Rashid',
          company: 'Medical Center West',
          email: 'mohammed@medicalcenter.ae',
          phone: '+971-50-7777777',
          location: 'Jumeirah',
          joinDate: '2024-03-20',
          totalSpent: 180000,
          projects: 3,
          lastService: '2025-12-20',
          status: 'Active',
          tier: 'Silver',
          notes: 'Healthcare facility, strict protocols'
        }
      ]
      setClients(mockClients)
      localStorage.setItem('homeware_crm_clients', JSON.stringify(mockClients))
    }
  }

  const loadServices = () => {
    const savedServices = localStorage.getItem('homeware_product_services')
    if (savedServices) {
      setServices(JSON.parse(savedServices))
    } else {
      // Initialize with mock service data
      const mockServices: Service[] = [
        {
          id: 1,
          name: 'Residential Cleaning',
          description: 'Complete home cleaning service',
          categoryId: 1,
          categoryName: 'Cleaning Services',
          basePrice: 2.5,
          price: 2.5,
          unit: 'sq ft',
          createdAt: new Date().toISOString(),
          rating: 4.8,
          duration: '2-4 hours',
          popularity: 95,
          featured: true
        },
        {
          id: 2,
          name: 'Commercial Office Cleaning',
          description: 'Professional office cleaning',
          categoryId: 1,
          categoryName: 'Cleaning Services',
          basePrice: 2.8,
          price: 2.8,
          unit: 'sq ft',
          createdAt: new Date().toISOString(),
          rating: 4.6,
          duration: '3-6 hours',
          popularity: 88,
          featured: false
        },
        {
          id: 3,
          name: 'Deep Cleaning Service',
          description: 'Intensive deep cleaning',
          categoryId: 1,
          categoryName: 'Cleaning Services',
          basePrice: 3.5,
          price: 3.5,
          unit: 'sq ft',
          createdAt: new Date().toISOString(),
          rating: 4.9,
          duration: '4-8 hours',
          popularity: 92,
          featured: true
        },
        {
          id: 4,
          name: 'Carpet Cleaning',
          description: 'Professional carpet cleaning and stain removal',
          categoryId: 2,
          categoryName: 'Specialized Services',
          basePrice: 3.0,
          price: 3.0,
          unit: 'sq ft',
          createdAt: new Date().toISOString(),
          rating: 4.7,
          duration: '2-3 hours',
          popularity: 85,
          featured: false
        },
        {
          id: 5,
          name: 'Floor Care',
          description: 'Floor maintenance and polishing',
          categoryId: 2,
          categoryName: 'Specialized Services',
          basePrice: 2.0,
          price: 2.0,
          unit: 'sq ft',
          createdAt: new Date().toISOString(),
          rating: 4.5,
          duration: '1-2 hours',
          popularity: 78,
          featured: false
        }
      ]
      setServices(mockServices)
      localStorage.setItem('homeware_product_services', JSON.stringify(mockServices))
    }
  }

  const selectedInvoice = invoices.find(i => i.id === selectedInvoiceId) || invoices[0]

  const stats = useMemo(() => ({
    total: invoices.length,
    draft: invoices.filter(i => i.status === 'Draft').length,
    sent: invoices.filter(i => i.status === 'Sent').length,
    paid: invoices.filter(i => i.status === 'Paid').length,
    totalValue: invoices.reduce((sum, i) => sum + i.total, 0),
    autoGenerated: invoices.filter(i => i.autoGenerated).length,
    avgPaymentTime: '5 days',
    vatTotal: invoices.reduce((sum, i) => sum + i.tax, 0)
  }), [invoices])

  const handleSendInvoice = (invoiceId: number) => {
    setInvoices(invoices.map(i =>
      i.id === invoiceId
        ? { ...i, status: 'Sent', sentAt: new Date().toISOString().replace('T', ' ').substring(0, 16) }
        : i
    ))
  }

  const handleMarkAsPaid = (invoiceId: number) => {
    setInvoices(invoices.map(i =>
      i.id === invoiceId
        ? {
            ...i,
            status: 'Paid',
            paymentStatus: 'Paid',
            paidAt: new Date().toISOString().split('T')[0],
            partialPayments: [...(i.partialPayments || []), { date: new Date().toISOString().split('T')[0], amount: i.total }]
          }
        : i
    ))
  }

  const handleGenerateInvoice = () => {
    if (!newInvoice.clientId || newInvoice.lineItems.length === 0) {
      alert('Please select a client and add at least one service')
      return
    }

    const invoiceDate = new Date().toISOString().split('T')[0]
    const dueDate = new Date(Date.now() + parseInt(newInvoice.paymentTerms) * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
    
    const subtotal = newInvoice.lineItems.reduce((sum, item) => sum + item.total, 0)
    const discountAmount = subtotal * (newInvoice.discount / 100)
    const taxableAmount = subtotal - discountAmount
    const tax = taxableAmount * newInvoice.vatRate
    const total = taxableAmount + tax

    const newInvoiceRecord = {
      id: Math.max(...invoices.map(i => i.id), 0) + 1,
      invoiceNumber: `INV-2025-${String(invoices.length + 1).padStart(3, '0')}`,
      clientId: newInvoice.clientId,
      clientName: newInvoice.clientName,
      clientCompany: newInvoice.clientCompany,
      clientEmail: newInvoice.clientEmail,
      clientPhone: newInvoice.clientPhone,
      clientLocation: newInvoice.clientLocation,
      jobId: Math.max(...invoices.map(i => i.jobId || 0), 0) + 1,
      serviceType: newInvoice.lineItems.map(item => item.serviceName).join(', '),
      invoiceDate,
      dueDate,
      status: 'Draft',
      lineItems: newInvoice.lineItems,
      subtotal,
      discount: discountAmount,
      tax,
      total,
      vatRate: newInvoice.vatRate,
      currencyCode: 'AED',
      paymentTerms: `${newInvoice.paymentTerms} days`,
      notes: newInvoice.notes || 'Payment due within specified terms. Bank details included below.',
      autoGenerated: false,
      sentAt: null,
      paymentStatus: 'Draft',
      partialPayments: []
    }
    
    setInvoices([...invoices, newInvoiceRecord])
    setShowNewInvoiceModal(false)
    setNewInvoice({
      clientId: 0,
      clientName: '',
      clientCompany: '',
      clientEmail: '',
      clientPhone: '',
      clientLocation: '',
      serviceType: '',
      lineItems: [],
      vatRate: 0.10,
      paymentTerms: '30',
      notes: '',
      discount: 0
    })
  }

  const handleClientSelect = (client: Client) => {
    setNewInvoice({
      ...newInvoice,
      clientId: client.id,
      clientName: client.name,
      clientCompany: client.company,
      clientEmail: client.email,
      clientPhone: client.phone,
      clientLocation: client.location
    })
    setShowClientDropdown(false)
    setClientSearchTerm('')
  }

  const handleServiceSelect = (service: Service) => {
    // Ask for quantity and area/size
    const quantity = parseFloat(prompt(`Enter quantity for ${service.name} (${service.unit}):`, '1') || '1')
    const area = parseFloat(prompt(`Enter area/size for ${service.name} (${service.unit}):`, '100') || '100')
    
    const unitPrice = service.basePrice * area
    const total = unitPrice * quantity
    
    const newLineItem: LineItem = {
      id: Date.now(),
      serviceId: service.id,
      serviceName: service.name,
      description: `${service.name} - ${area} ${service.unit} x ${quantity} ${quantity === 1 ? 'unit' : 'units'}`,
      quantity,
      unitPrice,
      unit: service.unit,
      total
    }
    
    setNewInvoice({
      ...newInvoice,
      lineItems: [...newInvoice.lineItems, newLineItem]
    })
    setShowServiceDropdown(false)
    setServiceSearchTerm('')
  }

  const handleRemoveLineItem = (itemId: number) => {
    setNewInvoice({
      ...newInvoice,
      lineItems: newInvoice.lineItems.filter(item => item.id !== itemId)
    })
  }

  const filteredClients = clients.filter(client =>
    client.name.toLowerCase().includes(clientSearchTerm.toLowerCase()) ||
    client.company.toLowerCase().includes(clientSearchTerm.toLowerCase()) ||
    client.email.toLowerCase().includes(clientSearchTerm.toLowerCase())
  )

  const filteredServices = services.filter(service =>
    service.name.toLowerCase().includes(serviceSearchTerm.toLowerCase()) ||
    service.categoryName.toLowerCase().includes(serviceSearchTerm.toLowerCase())
  )

  return (
    <div className="min-h-screen bg-white text-black p-6 space-y-8">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-emerald-500/10 rounded-lg">
              <FileText className="w-6 h-6 text-emerald-400" />
            </div>
            <h1 className="text-3xl font-bold text-black">
              Invoice Generator
            </h1>
          </div>
          <p className="text-gray-600">Auto-invoice generation, VAT compliance, and payment tracking</p>
        </div>
        <div className="flex items-center gap-3">
          <button className="flex items-center gap-2 px-4 py-2 bg-gray-100 border border-gray-300 rounded-xl hover:bg-gray-200 transition-all text-black">
            <Download className="w-4 h-4" />
            <span>Export All</span>
          </button>
          <button 
            onClick={() => setShowNewInvoiceModal(true)}
            className="flex items-center gap-2 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl transition-all shadow-lg shadow-emerald-900/20"
          >
            <Plus className="w-4 h-4" />
            <span>Create Invoice</span>
          </button>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: 'Total Invoices', value: stats.total, icon: FileText, color: 'text-blue-400', bg: 'bg-blue-500/10' },
          { label: 'Pending Payment', value: stats.sent, icon: Clock, color: 'text-amber-400', bg: 'bg-amber-500/10' },
          { label: 'Paid Invoices', value: stats.paid, icon: CheckCircle, color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
          { label: 'Total Revenue', value: `AED ${stats.totalValue.toLocaleString()}`, icon: Wallet, color: 'text-purple-400', bg: 'bg-purple-500/10' },
        ].map((stat, i) => (
          <div key={i} className="bg-white border border-gray-200 p-6 rounded-2xl shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <div className={`p-2 ${stat.bg.replace('bg-', 'bg-').replace('/10', '/20')} rounded-lg`}>
                <stat.icon className={`w-5 h-5 ${stat.color}`} />
              </div>
              <span className="text-xs font-medium text-gray-500 uppercase tracking-wider">Live</span>
            </div>
            <div className="text-2xl font-bold text-black mb-1">{stat.value}</div>
            <div className="text-sm text-gray-600">{stat.label}</div>
          </div>
        ))}
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Invoice List */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-sm">
            <div className="p-4 border-b border-gray-200 flex items-center justify-between">
              <h3 className="font-semibold text-black">Recent Invoices</h3>
              <div className="flex items-center gap-2">
                <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                  <Search className="w-4 h-4 text-gray-600" />
                </button>
                <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                  <Filter className="w-4 h-4 text-gray-600" />
                </button>
              </div>
            </div>
            <div className="divide-y divide-gray-200 max-h-[600px] overflow-y-auto">
              {invoices.map((invoice) => (
                <button
                  key={invoice.id}
                  onClick={() => setSelectedInvoiceId(invoice.id)}
                  className={`w-full p-4 text-left transition-all hover:bg-gray-50 ${
                    selectedInvoiceId === invoice.id ? 'bg-blue-50 border-l-2 border-blue-500' : ''
                  }`}
                >
                  <div className="flex justify-between items-start mb-1">
                    <span className="font-medium text-black">{invoice.invoiceNumber}</span>
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium uppercase tracking-wider ${
                      invoice.status === 'Paid' ? 'bg-green-100 text-green-800' :
                      invoice.status === 'Sent' ? 'bg-blue-100 text-blue-800' :
                      'bg-gray-100 text-gray-800'
                    }`}>
                      {invoice.status}
                    </span>
                  </div>
                  <div className="text-sm text-gray-600 mb-2">{invoice.clientName}</div>
                  <div className="flex justify-between items-center">
                    <span className="text-xs text-gray-500">{invoice.invoiceDate}</span>
                    <span className="font-semibold text-black">AED {invoice.total.toLocaleString()}</span>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Invoice Preview & Actions */}
        <div className="lg:col-span-8 space-y-6">
          {/* Invoice Preview */}
          <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-sm">
            <div className="p-6 border-b border-gray-200 flex items-center justify-between bg-linear-to-r from-blue-50 to-transparent">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-blue-100 rounded-xl">
                  <FileText className="w-6 h-6 text-blue-600" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-black">{selectedInvoice.invoiceNumber}</h2>
                  <p className="text-sm text-gray-600">Created on {selectedInvoice.invoiceDate}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-600">
                  <Printer className="w-5 h-5" />
                </button>
                <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-600">
                  <Mail className="w-5 h-5" />
                </button>
                <button className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-red-600">
                  <Trash2 className="w-5 h-5" />
                </button>
              </div>
            </div>

            <div className="p-8 space-y-8">
              {/* Client & Status Info */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="space-y-4">
                  <div>
                    <label className="text-[10px] font-medium text-gray-500 uppercase tracking-widest">Bill To</label>
                    <h3 className="text-lg font-bold text-black mt-1">{selectedInvoice.clientName}</h3>
                    <p className="text-sm text-gray-600">Client ID: #{selectedInvoice.clientId}</p>
                  </div>
                  <div className="flex items-center gap-6">
                    <div>
                      <label className="text-[10px] font-medium text-gray-500 uppercase tracking-widest">Due Date</label>
                      <p className="text-sm text-black font-medium mt-1">{selectedInvoice.dueDate}</p>
                    </div>
                    <div>
                      <label className="text-[10px] font-medium text-gray-500 uppercase tracking-widest">Terms</label>
                      <p className="text-sm text-black font-medium mt-1">{selectedInvoice.paymentTerms}</p>
                    </div>
                  </div>
                </div>
                <div className="bg-gray-50 rounded-2xl p-6 border border-gray-200">
                  <div className="flex justify-between items-center mb-4">
                    <span className="text-sm text-gray-600">Payment Status</span>
                    <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                      selectedInvoice.status === 'Paid' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'
                    }`}>
                      {selectedInvoice.status.toUpperCase()}
                    </span>
                  </div>
                  <div className="text-3xl font-bold text-black mb-2">
                    AED {selectedInvoice.total.toLocaleString()}
                  </div>
                  {selectedInvoice.autoGenerated && (
                    <div className="flex items-center gap-2 text-xs text-green-600">
                      <Zap className="w-3 h-3" />
                      <span>AI-Generated Invoice</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Line Items Table */}
              <div className="space-y-4">
                <label className="text-[10px] font-medium text-gray-500 uppercase tracking-widest">Service Details</label>
                <div className="border border-gray-200 rounded-xl overflow-hidden">
                  <table className="w-full text-left text-sm">
                    <thead className="bg-gray-50 text-gray-600">
                      <tr>
                        <th className="px-4 py-3 font-medium">Description</th>
                        <th className="px-4 py-3 font-medium text-center">Qty</th>
                        <th className="px-4 py-3 font-medium text-right">Unit Price</th>
                        <th className="px-4 py-3 font-medium text-right">Total</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                      {selectedInvoice.lineItems.map((item: any, i: number) => (
                        <tr key={i} className="text-gray-900">
                          <td className="px-4 py-4">{item.description}</td>
                          <td className="px-4 py-4 text-center">{item.quantity}</td>
                          <td className="px-4 py-4 text-right">AED {item.unitPrice.toLocaleString()}</td>
                          <td className="px-4 py-4 text-right font-medium text-black">
                            AED {(item.quantity * item.unitPrice).toLocaleString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Summary */}
              <div className="flex justify-end">
                <div className="w-full md:w-64 space-y-3">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">Subtotal</span>
                    <span className="text-black">AED {selectedInvoice.subtotal.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">VAT ({(selectedInvoice.vatRate * 100).toFixed(0)}%)</span>
                    <span className="text-black">AED {selectedInvoice.tax.toLocaleString()}</span>
                  </div>
                  <div className="pt-3 border-t border-gray-200 flex justify-between items-center">
                    <span className="font-bold text-black">Total Amount</span>
                    <span className="text-xl font-bold text-green-600">
                      AED {selectedInvoice.total.toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>

              {/* Actions Footer */}
              <div className="pt-6 border-t border-gray-200 flex flex-wrap gap-3">
                {selectedInvoice.status === 'Draft' && (
                  <>
                    <button
                      onClick={() => handleSendInvoice(selectedInvoice.id)}
                      className="flex-1 min-w-[140px] flex items-center justify-center gap-2 px-4 py-3 bg-green-600 hover:bg-green-500 text-white rounded-xl transition-all font-semibold"
                    >
                      <Send className="w-4 h-4" />
                      Send Invoice
                    </button>
                    <button className="flex-1 min-w-[140px] px-4 py-3 bg-gray-100 hover:bg-gray-200 text-black rounded-xl transition-all font-semibold">
                      Edit Draft
                    </button>
                  </>
                )}

                {selectedInvoice.status === 'Sent' && (
                  <>
                    <button
                      onClick={() => handleMarkAsPaid(selectedInvoice.id)}
                      className="flex-1 min-w-[140px] flex items-center justify-center gap-2 px-4 py-3 bg-green-600 hover:bg-green-500 text-white rounded-xl transition-all font-semibold"
                    >
                      <CheckCircle className="w-4 h-4" />
                      Mark as Paid
                    </button>
                    <button className="flex-1 min-w-[140px] px-4 py-3 bg-amber-100 hover:bg-amber-200 text-amber-800 rounded-xl transition-all font-semibold border border-amber-300">
                      Partial Payment
                    </button>
                  </>
                )}

                <button className="flex items-center gap-2 px-6 py-3 bg-gray-100 hover:bg-gray-200 text-black rounded-xl transition-all font-semibold">
                  <Download className="w-4 h-4" />
                  PDF
                </button>
              </div>
            </div>
          </div>

          {/* Compliance & AI Insights */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-green-50 border border-green-200 p-4 rounded-2xl flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-green-600 mt-0.5" />
              <div>
                <h4 className="text-sm font-bold text-green-800">VAT Compliant</h4>
                <p className="text-xs text-green-600 mt-1">This invoice meets all FTA requirements for tax reporting in the UAE.</p>
              </div>
            </div>
            <div className="bg-blue-50 border border-blue-200 p-4 rounded-2xl flex items-start gap-3">
              <Zap className="w-5 h-5 text-blue-600 mt-0.5" />
              <div>
                <h4 className="text-sm font-bold text-blue-800">AI Prediction</h4>
                <p className="text-xs text-blue-600 mt-1">Based on client history, this invoice is likely to be paid within 4 days.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* New Invoice Modal */}
      {showNewInvoiceModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white border border-gray-200 rounded-3xl p-8 max-w-4xl w-full shadow-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 bg-green-100 rounded-lg">
                <Plus className="w-5 h-5 text-green-600" />
              </div>
              <h3 className="text-xl font-bold text-black">Create New Invoice</h3>
            </div>

            <div className="space-y-6 mb-8">
              {/* Client Selection */}
              <div className="relative">
                <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest mb-2">Select Client</label>
                <div className="relative">
                  <button
                    onClick={() => setShowClientDropdown(!showClientDropdown)}
                    className="w-full bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-left text-black focus:outline-none focus:ring-2 focus:ring-green-500/50 transition-all flex items-center justify-between"
                  >
                    <div className="flex items-center gap-3">
                      <User className="w-4 h-4 text-gray-500" />
                      {newInvoice.clientId ? (
                        <div>
                          <div className="font-medium">{newInvoice.clientName}</div>
                          <div className="text-sm text-gray-500">{newInvoice.clientCompany}</div>
                        </div>
                      ) : (
                        <span className="text-gray-500">Select a client...</span>
                      )}
                    </div>
                    <ChevronRight className={`w-4 h-4 text-gray-400 transition-transform ${showClientDropdown ? 'rotate-90' : ''}`} />
                  </button>
                  
                  {showClientDropdown && (
                    <div className="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-xl shadow-lg max-h-60 overflow-y-auto">
                      <div className="p-2">
                        <input
                          type="text"
                          placeholder="Search clients..."
                          value={clientSearchTerm}
                          onChange={(e) => setClientSearchTerm(e.target.value)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-green-500/50"
                        />
                      </div>
                      <div className="max-h-48 overflow-y-auto">
                        {filteredClients.map((client) => (
                          <button
                            key={client.id}
                            onClick={() => handleClientSelect(client)}
                            className="w-full px-4 py-3 text-left hover:bg-gray-50 transition-colors border-b border-gray-100 last:border-b-0"
                          >
                            <div className="flex items-center gap-3">
                              <div className="p-2 bg-blue-100 rounded-lg">
                                <Building2 className="w-4 h-4 text-blue-600" />
                              </div>
                              <div>
                                <div className="font-medium text-black">{client.name}</div>
                                <div className="text-sm text-gray-600">{client.company}</div>
                                <div className="text-xs text-gray-500">{client.location}</div>
                              </div>
                            </div>
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Selected Client Info */}
              {newInvoice.clientId > 0 && (
                <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                    <div>
                      <span className="text-gray-500">Email:</span>
                      <div className="font-medium text-black">{newInvoice.clientEmail}</div>
                    </div>
                    <div>
                      <span className="text-gray-500">Phone:</span>
                      <div className="font-medium text-black">{newInvoice.clientPhone}</div>
                    </div>
                    <div>
                      <span className="text-gray-500">Location:</span>
                      <div className="font-medium text-black">{newInvoice.clientLocation}</div>
                    </div>
                  </div>
                </div>
              )}

              {/* Service Selection */}
              <div className="relative">
                <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest mb-2">Add Services</label>
                <div className="relative">
                  <button
                    onClick={() => setShowServiceDropdown(!showServiceDropdown)}
                    className="w-full bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-left text-black focus:outline-none focus:ring-2 focus:ring-green-500/50 transition-all flex items-center justify-between"
                  >
                    <div className="flex items-center gap-3">
                      <Package className="w-4 h-4 text-gray-500" />
                      <span className="text-gray-500">Add a service...</span>
                    </div>
                    <ChevronRight className={`w-4 h-4 text-gray-400 transition-transform ${showServiceDropdown ? 'rotate-90' : ''}`} />
                  </button>
                  
                  {showServiceDropdown && (
                    <div className="absolute z-10 w-full mt-1 bg-white border border-gray-200 rounded-xl shadow-lg max-h-60 overflow-y-auto">
                      <div className="p-2">
                        <input
                          type="text"
                          placeholder="Search services..."
                          value={serviceSearchTerm}
                          onChange={(e) => setServiceSearchTerm(e.target.value)}
                          className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-green-500/50"
                        />
                      </div>
                      <div className="max-h-48 overflow-y-auto">
                        {filteredServices.map((service) => (
                          <button
                            key={service.id}
                            onClick={() => handleServiceSelect(service)}
                            className="w-full px-4 py-3 text-left hover:bg-gray-50 transition-colors border-b border-gray-100 last:border-b-0"
                          >
                            <div className="flex items-center gap-3">
                              <div className="p-2 bg-green-100 rounded-lg">
                                <Calculator className="w-4 h-4 text-green-600" />
                              </div>
                              <div className="flex-1">
                                <div className="font-medium text-black">{service.name}</div>
                                <div className="text-sm text-gray-600">{service.categoryName}</div>
                                <div className="text-xs text-gray-500">AED {service.basePrice}/{service.unit}</div>
                              </div>
                            </div>
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Line Items */}
              {newInvoice.lineItems.length > 0 && (
                <div className="space-y-3">
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest">Selected Services</label>
                  <div className="space-y-2">
                    {newInvoice.lineItems.map((item) => (
                      <div key={item.id} className="flex items-center justify-between bg-gray-50 border border-gray-200 rounded-lg p-3">
                        <div className="flex-1">
                          <div className="font-medium text-black">{item.serviceName}</div>
                          <div className="text-sm text-gray-600">{item.description}</div>
                        </div>
                        <div className="text-right mr-3">
                          <div className="font-medium text-black">AED {item.total.toLocaleString()}</div>
                          <div className="text-sm text-gray-500">{item.quantity} x AED {item.unitPrice.toLocaleString()}</div>
                        </div>
                        <button
                          onClick={() => handleRemoveLineItem(item.id)}
                          className="p-1 hover:bg-red-100 rounded text-red-600 transition-colors"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                  
                  {/* Subtotal */}
                  <div className="flex justify-end pt-3 border-t border-gray-200">
                    <div className="w-64 space-y-2">
                      <div className="flex justify-between text-sm">
                        <span className="text-gray-600">Subtotal:</span>
                        <span className="font-medium text-black">
                          AED {newInvoice.lineItems.reduce((sum, item) => sum + item.total, 0).toLocaleString()}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Invoice Settings */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest mb-2">VAT Rate</label>
                  <select
                    value={newInvoice.vatRate * 100}
                    onChange={(e) => setNewInvoice({ ...newInvoice, vatRate: parseFloat(e.target.value) / 100 })}
                    className="w-full bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-black focus:outline-none focus:ring-2 focus:ring-green-500/50 transition-all appearance-none"
                  >
                    <option value="0">0%</option>
                    <option value="5">5%</option>
                    <option value="10">10%</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest mb-2">Payment Terms</label>
                  <select
                    value={newInvoice.paymentTerms}
                    onChange={(e) => setNewInvoice({ ...newInvoice, paymentTerms: e.target.value })}
                    className="w-full bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-black focus:outline-none focus:ring-2 focus:ring-green-500/50 transition-all appearance-none"
                  >
                    <option value="7">7 days</option>
                    <option value="15">15 days</option>
                    <option value="30">30 days</option>
                    <option value="60">60 days</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest mb-2">Discount (%)</label>
                  <input
                    type="number"
                    value={newInvoice.discount}
                    onChange={(e) => setNewInvoice({ ...newInvoice, discount: parseFloat(e.target.value) || 0 })}
                    placeholder="0"
                    min="0"
                    max="100"
                    className="w-full bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-black focus:outline-none focus:ring-2 focus:ring-green-500/50 transition-all"
                  />
                </div>
              </div>

              {/* Notes */}
              <div>
                <label className="block text-xs font-medium text-gray-500 uppercase tracking-widest mb-2">Notes</label>
                <textarea
                  value={newInvoice.notes}
                  onChange={(e) => setNewInvoice({ ...newInvoice, notes: e.target.value })}
                  placeholder="Additional notes for the invoice..."
                  rows={3}
                  className="w-full bg-gray-50 border border-gray-300 rounded-xl px-4 py-3 text-black focus:outline-none focus:ring-2 focus:ring-green-500/50 transition-all resize-none"
                />
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => setShowNewInvoiceModal(false)}
                className="flex-1 px-4 py-3 bg-gray-100 hover:bg-gray-200 text-black rounded-xl font-semibold transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleGenerateInvoice}
                disabled={newInvoice.lineItems.length === 0}
                className="flex-1 px-4 py-3 bg-green-600 hover:bg-green-500 disabled:bg-gray-300 disabled:cursor-not-allowed text-white rounded-xl font-semibold transition-all shadow-lg shadow-green-500/20"
              >
                Create Invoice
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
